name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python, Poetry and Dependencies
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{matrix.python-version}}

    - name: Linting with ruff
      run: |
        poetry run ruff .
        poetry run ruff format --check .

    - name: Typechecking with mypy
      run: |
        poetry run mypy .

    - name: Test with pytest
      run: |
        poetry run pytest
