name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    env:
      FLIT_USERNAME: __token__
      FLIT_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
      FLIT_INDEX_URL: https://test.pypi.org/legacy/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit
        python -m flit install --only-deps --deps develop
    - name: Linting with ruff
      run: |
        python -m ruff .
        python -m ruff format --check .
    - name: Typechecking with mypy
      run: |
        python -m mypy .
    - name: Test with pytest
      run: |
        pytest
    - name: Publish to TestPyPi
      shell: bash
      run: |
        python -m flit publish

